# Generated by Django 3.2 on 2022-06-14 05:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='content_rate',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='rate',
            name='design_rate',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='rate',
            name='total_rate',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rate',
            name='usability_rate',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
